<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'5pyN5Yqh6aG555uu');
$cfg_Cs[3]=array(0,1,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[4]=array(3,1,1,'5YiG57G75LiA');
$cfg_Cs[5]=array(3,1,1,'5YiG57G75LqM');
$cfg_Cs[6]=array(3,1,1,'5YiG57G75LiJ');
$cfg_Cs[7]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[8]=array(7,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[9]=array(7,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[10]=array(7,1,1,'572R56uZ5YWs5ZGK');
$cfg_Cs[11]=array(0,17,1,'5Lq65omN5oub6IGY');
$cfg_Cs[12]=array(0,1,1,'5Zyo57q/55WZ6KiA');
$cfg_Cs[13]=array(0,1,1,'6IGU57O75oiR5Lus');
?>