<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1974,2009);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2143,2172);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2266,2295);
$z[4][4]['name']="position";
$z[5]=Array("field","",2393,2414);
$z[5][4]['name']="content";
$z[6]=Array("include","",2507,2544);
$z[6][4]['filename']="footer.htm";

?>