<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1128,1165);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1350,1376);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("field","",1516,1545);
$z[4][4]['name']="typename";
$z[5]=Array("field","",2223,2244);
$z[5][4]['name']="content";
$z[6]=Array("include","",2301,2340);
$z[6][4]['filename']="footer_m.htm";

?>