<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1973,2008);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2145,2174);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2268,2297);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n  <div class=\"hrBox\">\r\n    <div class=\"hrBoxL\">\r\n      <ul>\r\n        <li><span>所需职位：</span></li>\r\n        <li class=\"bgWhite\">所需人数：</li>\r\n        <li class=\"haode\">具体要求：</li>\r\n      </ul>\r\n      <div class=\"clear\"></div>\r\n    </div>\r\n	<div class=\"hrBoxR\">\r\n      <ul>\r\n        <li class=\"topline\"><span class=\"fl\">[field:title/]</span><a href=\"http://wpa.qq.com/msgrd?v=3&uin=6009709&site=qq&menu=yes\" class=\"fr\" title=\"应聘此职位\"><img src=\"/skin/images/re.gif\" width=\"90\" height=\"26\" /></a>\r\n          <div class=\"clear\"></div>\r\n        </li>\r\n        <li class=\"bgWhite\">[field:renshu/]\r\n          <div class=\"clear\"></div>\r\n        </li>\r\n        <li class=\"haode\">\r\n		[field:body/]\r\n		</li>\r\n      </ul>\r\n      <div class=\"clear\"></div>\r\n    </div>\r\n    <div class=\"clear\"></div>\r\n  </div>\r\n  ",2347,3218);
$z[5][4]['pagesize']="6";
$z[6]=Array("pagelist","",3240,3299);
$z[6][4]['istitem']="index,pre,next,end,";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",3342,3379);
$z[7][4]['filename']="footer.htm";

?>