<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1128,1165);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1325,1351);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("global","",1362,1388);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n        ",2176,2432);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[6]=Array("field","",2529,2548);
$z[6][4]['name']="title";
$z[7]=Array("field","",2594,2612);
$z[7][4]['name']="body";
$z[8]=Array("prenext","",2633,2658);
$z[8][4]['get']="pre";
$z[9]=Array("prenext","",2664,2690);
$z[9][4]['get']="next";
$z[10]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2696,2821);
$z[10][4]['typeid']="0";
$z[10][4]['row']="1";
$z[11]=Array("include","",2873,2912);
$z[11][4]['filename']="footer_m.htm";

?>