<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1970,2005);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2138,2167);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2261,2290);
$z[4][4]['name']="position";
$z[5]=Array("channel","\r\n		<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n		",2355,2468);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[6]=Array("field","",2587,2606);
$z[6][4]['name']="title";
$z[7]=Array("field","",2869,2921);
$z[7][4]['name']="pubdate";
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("field","",2954,2974);
$z[8][4]['name']="writer";
$z[9]=Array("field","",3023,3050);
$z[9][4]['name']="phpurl";
$z[10]=Array("field","",3074,3097);
$z[10][4]['name']="id";
$z[11]=Array("field","",3102,3126);
$z[11][4]['name']="mid";
$z[12]=Array("field","",3357,3375);
$z[12][4]['name']="body";
$z[13]=Array("type","<a href=\"[field:typelink /]\" title=\"返回列表\" class=\"returnlist\">返回列表</a>",3389,3514);
$z[13][4]['typeid']="0";
$z[13][4]['row']="1";
$z[14]=Array("include","",3551,3588);
$z[14][4]['filename']="footer.htm";

?>