<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1131,1168);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1328,1354);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("global","",1365,1391);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("field","",1531,1550);
$z[5][4]['name']="title";
$z[6]=Array("global","",1828,1853);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n        ",2214,2470);
$z[7][4]['type']="son";
$z[7][4]['row']="10";
$z[8]=Array("field","",2567,2586);
$z[8][4]['name']="title";
$z[9]=Array("field","",2632,2650);
$z[9][4]['name']="body";
$z[10]=Array("prenext","",2671,2696);
$z[10][4]['get']="pre";
$z[11]=Array("prenext","",2702,2728);
$z[11][4]['get']="next";
$z[12]=Array("type","<a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2734,2859);
$z[12][4]['typeid']="0";
$z[12][4]['row']="1";
$z[13]=Array("include","",2911,2950);
$z[13][4]['filename']="footer_m.htm";

?>