<?php
$z[0]=Array("global","",1200,1225);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("field","(@me==\"\")? @me=\"   class='cur'  \":@me=\"\";",1607,1698);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channel","\r\n	  <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> </li>\r\n      ",1726,1937);
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li><a href='~typelink~' class='cur'>~typename~</a></li>";

?>