<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1971,2006);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2142,2171);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2265,2294);
$z[4][4]['name']="position";
$z[5]=Array("field","",2392,2413);
$z[5][4]['name']="content";
$z[6]=Array("include","",2506,2543);
$z[6][4]['filename']="footer.htm";

?>