<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1131,1168);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1353,1379);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("field","",1519,1548);
$z[4][4]['name']="typename";
$z[5]=Array("field","",2226,2247);
$z[5][4]['name']="content";
$z[6]=Array("include","",2304,2343);
$z[6][4]['filename']="footer_m.htm";

?>