<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1973,2008);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2141,2170);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2264,2293);
$z[4][4]['name']="position";
$z[5]=Array("channel","\r\n		<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n		",2366,2479);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[6]=Array("list","\r\n	<li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" width=\"298\" height=\"224\"/></a> <a href=\"[field:arcurl/]\" class=\"protxt\">[field:title/]</a> </li>\r\n	",2561,2781);
$z[6][4]['pagesize']="6";
$z[7]=Array("pagelist","",2841,2900);
$z[7][4]['istitem']="index,pre,next,end,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2949,2986);
$z[8][4]['filename']="footer.htm";

?>