<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1970,2005);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2135,2164);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2258,2287);
$z[4][4]['name']="position";
$z[5]=Array("channel","\r\n		<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n		",2349,2462);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[6]=Array("list","\r\n	<li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a>\r\n      <p class=\"newslisttime\"><span class=\"fl\">[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span><a href=\"[field:arcurl/]\" title=\"更多\">Readmore</a></p>\r\n      <p class=\"newstxt\">　　[field:infos/]...</p>\r\n    </li>\r\n	",2543,2896);
$z[6][4]['pagesize']="6";
$z[6][4]['infolen']="150";
$z[7]=Array("pagelist","",2959,3018);
$z[7][4]['istitem']="index,pre,next,end,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",3061,3098);
$z[8][4]['filename']="footer.htm";

?>