<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1131,1168);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1328,1354);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("global","",1365,1391);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("field","",1531,1560);
$z[5][4]['name']="typename";
$z[6]=Array("global","",1838,1863);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n        ",2227,2483);
$z[7][4]['type']="son";
$z[7][4]['row']="10";
$z[8]=Array("list","\r\n	  <li class=\"news1\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a> </li>\r\n	  ",2598,2832);
$z[8][4]['pagesize']="6";
$z[8][4]['infolen']="150";
$z[9]=Array("pagelist","",2883,2942);
$z[9][4]['istitem']="index,pre,next,end,";
$z[9][4]['listsize']="5";
$z[10]=Array("include","",3004,3043);
$z[10][4]['filename']="footer_m.htm";

?>