<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1970,2005);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2138,2167);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2261,2290);
$z[4][4]['name']="position";
$z[5]=Array("channel","\r\n		<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n		",2363,2476);
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['col']="1";
$z[6]=Array("list","\r\n	<li> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" width=\"298\" height=\"224\"/></a> <a href=\"[field:arcurl/]\" class=\"protxt\">[field:title/]</a> </li>\r\n	",2558,2787);
$z[6][4]['pagesize']="6";
$z[7]=Array("pagelist","",2847,2906);
$z[7][4]['istitem']="index,pre,next,end,";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2955,2992);
$z[8][4]['filename']="footer.htm";

?>