<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1131,1168);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1328,1354);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("global","",1365,1391);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("field","",1531,1560);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li> <a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">&#xe60c;</span>\r\n          <dl>\r\n          </dl>\r\n        </li>\r\n        ",2211,2467);
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[7]=Array("list","\r\n	  <li class=\"news4\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\"> <span>[field:title/]</span> </a> </li>\r\n	  ",2582,2794);
$z[7][4]['pagesize']="6";
$z[8]=Array("pagelist","",2845,2904);
$z[8][4]['istitem']="index,pre,next,end,";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2966,3005);
$z[9][4]['filename']="footer_m.htm";

?>