<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",2060,2095);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2229,2258);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2352,2381);
$z[4][4]['name']="position";
$z[5]=Array("include","",4830,4867);
$z[5][4]['filename']="footer.htm";

?>