<?php
$z[0]=Array("field","",348,367);
$z[0][4]['name']="title";
$z[1]=Array("global","",368,394);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1200,1237);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1397,1423);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("global","",1434,1460);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("include","",2668,2707);
$z[5][4]['filename']="footer_m.htm";

?>