<?php
$z[0]=Array("field","",345,364);
$z[0][4]['name']="title";
$z[1]=Array("global","",365,391);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1197,1234);
$z[2][4]['filename']="head_m.htm";
$z[3]=Array("global","",1394,1420);
$z[3][4]['name']="cfg_dianhua";
$z[4]=Array("global","",1431,1457);
$z[4][4]['name']="cfg_dianhua";
$z[5]=Array("include","",2665,2704);
$z[5][4]['filename']="footer_m.htm";

?>