<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",2057,2092);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",2226,2255);
$z[3][4]['name']="typename";
$z[4]=Array("field","",2349,2378);
$z[4][4]['name']="position";
$z[5]=Array("include","",4827,4864);
$z[5][4]['filename']="footer.htm";

?>