<?php
$z[0]=Array("global","",264,290);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1960,1995);
$z[1][4]['filename']="head.htm";
$z[2]=Array("channel","\r\n		<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n		",2307,2420);
$z[2][4]['row']="10";
$z[2][4]['type']="son";
$z[2][4]['col']="1";
$z[3]=Array("list","\r\n	<li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a>\r\n      <p class=\"newslisttime\"><span class=\"fl\">2015/05/18</span><a href=\"[field:arcurl/]\" title=\"更多\">Readmore</a></p>\r\n      <p class=\"newstxt\">　　[field:infos/]...</p>\r\n    </li>\r\n	",2501,2817);
$z[3][4]['pagesize']="6";
$z[3][4]['infolen']="150";
$z[4]=Array("pagelist","",2880,2939);
$z[4][4]['istitem']="index,pre,next,end,";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",2982,3019);
$z[5][4]['filename']="footer.htm";

?>